// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwc8T1sXnaOi9qeNuMU3qk7L-PvOwXHNU',
    appId: '1:540695093297:web:5c2589d5c9840db4d97510',
    messagingSenderId: '540695093297',
    projectId: 'movies-app-13b30',
    authDomain: 'movies-app-13b30.firebaseapp.com',
    storageBucket: 'movies-app-13b30.firebasestorage.app',
    measurementId: 'G-3KXHLNL85T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfagz-8QLhTJtFZSCX6zUxl-PFjJkrKhY',
    appId: '1:540695093297:android:354d96e02f3b19ecd97510',
    messagingSenderId: '540695093297',
    projectId: 'movies-app-13b30',
    storageBucket: 'movies-app-13b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrOiZsDCTfeBwr9K2VnQ1MM78jBFU5d-Y',
    appId: '1:540695093297:ios:768ee40f412da0aad97510',
    messagingSenderId: '540695093297',
    projectId: 'movies-app-13b30',
    storageBucket: 'movies-app-13b30.firebasestorage.app',
    androidClientId:
        '540695093297-66f435slkg3ka6reolkgulp0ic5gdnca.apps.googleusercontent.com',
    iosClientId:
        '540695093297-l1rf17mfgkoht1ngfcokkliddhns2i1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.routeMoviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrOiZsDCTfeBwr9K2VnQ1MM78jBFU5d-Y',
    appId: '1:540695093297:ios:768ee40f412da0aad97510',
    messagingSenderId: '540695093297',
    projectId: 'movies-app-13b30',
    storageBucket: 'movies-app-13b30.firebasestorage.app',
    androidClientId:
        '540695093297-66f435slkg3ka6reolkgulp0ic5gdnca.apps.googleusercontent.com',
    iosClientId:
        '540695093297-l1rf17mfgkoht1ngfcokkliddhns2i1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.routeMoviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwc8T1sXnaOi9qeNuMU3qk7L-PvOwXHNU',
    appId: '1:540695093297:web:a022d4aeed619811d97510',
    messagingSenderId: '540695093297',
    projectId: 'movies-app-13b30',
    authDomain: 'movies-app-13b30.firebaseapp.com',
    storageBucket: 'movies-app-13b30.firebasestorage.app',
    measurementId: 'G-WL44K8TTKL',
  );
}
